### ISSUE TITLE
📋 [TASK] - Gameerstellung

### ISSUE THREAD

**Issue by FrederikHa** [Nope-Cardgame/Backend#16]
### 💭 Vorstellung/Wunsch

Konzeptionelle Fragen klären und ggf. Dokumentieren:
 - [x] Was passiert wenn ein Spieler das Spiel ablehnt? Werden die anderen benachrichtigt?
 - [x] Gibt es ein Timeout um ein Spiel anzunehmen?
 - [x] Kann man mehrere Spiele annehmen? Werden bei Annahme alle anderen abgelehnt?
 - [x] Kann man mehrere Spiele gleichzeitig mit dem selben Websocket spielen?
 - [x] Kann eine angenommene Einladung wieder zurückgezogen werden?
 
Umsetzung der Spielstartfunktionen
 - [x] Beim POST auf `/game` wird ein Gameobjekt (mit Playern) erzeugt und die Einladung gesendet
 - [x] Die Clients können Einladungen annehmen oder ablehnen
 - [x] Wenn der letzte Client die Einladung annimmt wird eine interne Spielstartfunktion aufgerufen.

### 📈 Nutzen

Das Spiel kann gestartet werden und die Clients können ihre Initialisierung testen.

**Comment by HannesNowak** [comment]
> Was passiert wenn ein Spieler das Spiel ablehnt? Werden die anderen benachrichtigt?

Ich hätte gesagt, wenn ein Game nicht mit der angefragten Konstellation zustande kommt, wird dieses nicht erstellt. Das heißt es reicht, dass ein Spieler absagt, damit die Spieleinladung verworfen wird.
> Gibt es ein Timeout um ein Spiel anzunehmen?

Timeout ist denke ich schwer festzulegen, da die Einladungen sind zu lange auf dem Server verweilen sollten, die Zusage aber eventuell etwas dauern könnte, gerade wenn Clients diese noch manuell tätigen wollen. Im Zweifel auch wieder 10s?
> Kann man mehrere Spiele annehmen? Werden bei Annahme alle anderen abgelehnt?
> Kann man mehrere Spiele gleichzeitig mit dem selben Websocket spielen?

Als User können mehrere Spiele angenommen werden, allerdings da unser Player die WebSocket-Verbindung widerspiegelt dürfte nur ein WebSocket an einem Game gleichzeitig teilnehmen, da wir sonst bei gesendeten Events nicht unterscheiden könnten, welches Spiel er meint und im Zweifel beim falschen Spiel bannen/ausschließlich, etc.
> Kann eine angenommene Einladung wieder zurückgezogen werden?

Das Zurückziehen von Zusagen zu Einladungen ist abhängig vom Timeout... Grundsätzlich wäre es möglich, da die Clients das `ready`-Event erneut mit `"accept": false` senden könnten, wodurch die Einladung dann abgebrochen wird.

**Comment by HannesNowak** [comment]
Ein Timeout wird definitiv benötigt, da es sonst bei einem Turnier zu einem Stoppen führen kann. Somit muss ein Spieler im Zweifel auch disqualifiziert werden, sobald dieser sein nächstes Spiel nicht im gewissen Zeitrahmen annimmt.
Das mit dem `ready` finde ich gut. Das wäre quasi, dass einer eine Game-Lobby aufmacht, sich die Spieler dann per `accepted` dort zusammenfinden und im Anschluss, wenn alle ebenfalls `ready` sind dann wird gestartet. Dabei wäre es nur wieder beim Turnier kritisch, da für ein `ready` ein Timeout nicht sinnvoll wäre, das Spiel dann aber ebenso aufgehalten werden könnte.
Somit würde ich ein forceReady einbauen, sodass bei der Einladung bereits feststeht, dass es keine 'Lobby' gibt, sondern nach Zustimmung aller Spieler das Spiel direkt startet.

**Comment by XX123Fabian123XX** [comment]
Bei dem Timeout stimme ich Hannes zu. Das mit dem `ready` und `accepted` finde ich auch eine gute Idee.
