### ISSUE TITLE
Spiellogik

### ISSUE THREAD

**Issue by FrederikHa** [Nope-Cardgame/Backend#17]
# 💭 Vorstellung/Wunsch
Implementierung der elementaren Spiellogik. Die Aktionskarten und Turniere werden erstmal ausgelassen:
 - [x] Spiele können gestartet werden
 - [x] Das Spiel wird korrekt mit einem Zustandsautomaten verwaltet
 - [x] alle Clients im Spiel bekommen updates wenn sich der Spielzustand ändert
 - [x] Spielzüge werden korrekt ausgewertet

# 📈 Nutzen
ein rüdimentärer Spielablauf kann durch die Clients ausprobiert werden

# 🔗 Abhängigkeit
[Schnittstellen Dokumentation](https://github.com/Nope-Cardgame/Doku/pull/3) muss evtl. erweitert werden

**Comment by HannesNowak** [comment]
> Das Spiel wird korrekt mit einem Zustandsautomaten verwaltet

Diesbezüglich könnte das package [XState](https://stately.ai/docs/xstate) hilfreich sein
