### ISSUE TITLE
📋 [TASK] - Spielkarten

### ISSUE THREAD

**Issue by FrederikHa** [Nope-Cardgame/Backend#27]
### 💭 Vorstellung/Wunsch

Wir wollen die Karten so speichern, dass 
 - [x] sie einfach zu vergleichen sind.
 - [x] die verwendeten Karten in einem Spiel variable sind (?)
 - [x] auch ohne Aktionskarten gespielt werden kann.

Dazu sollten wir folgende Ideen evaluieren:
 - Karten als Datenbankobjekte in Tabelle (die Tabelle hat initial Einträge und **nie** erweitert.
 - Karten als Klasse mit privatem Konstruktor und readonly Instancen (Enum)
 - Karten als Config JSON die bei Serverstart eingelesen wird. 

### 📈 Nutzen

viel Funktionalität mit möglichst wenig Aufwand

**Comment by HannesNowak** [comment]
Karten sind jetzt ebenfalls als 'enum' im Schema angelegt, ähnlich zum CardType
