### ISSUE TITLE
📋 [TASK] - Datenbankklassen

### ISSUE THREAD

**Issue by HannesNowak** [Nope-Cardgame/Backend#7]
### 💭 Vorstellung/Wunsch

- grundlegende Funktionen aller benötigten Datenklassen
- Relationen der Tabellen abgebildet auf die Klassen
- Speichern neuer Objekte in die Datenbank
- Erstellen der Datenbank durch das TypeScript-Projekt

### 📈 Nutzen

- einfaches Verwenden der Datenklassen
- Grundlage für die weitere Implementierung
- Abbildung des ER-Diagramms in Klassen
- leichtes Speichern in die Datenbank

### 🔗 Abhängigkeit

- ER-Diagramm sollte erstellt sein

**Comment by XX123Fabian123XX** [comment]
- Finde ich soweit eine richtige gute Umsetzung 👍 
Ich hätte noch ein paar kleine Änderungsvorschläge (wahrscheinlich werde ich noch einen Commit machen, der diese umsetzt):
- bei den Enums in den Datenbankklassen würde ich diese als String definieren. Dadurch würde diese in der Datenbank auch als String gespeichert werden, sonst werden nämlich nur Zahlen gespeichert. Oder gibt es eine Möglichkeit einer Zahl den Wert eines Enums zuzuordnen??
```typescript

export enum CardColor {
    RED = "red",
    GREEN = "green",
    BLUE = "blue",
    YELLOW = "yellow",
    RED_GREEN = "redGreen",
    RED_BLUE = "redBlue",
    RED_YELLOW = "redYellow",
    GREEN_BLUE = "greenBlue",
    GREEN_YELLOW = "greenYellow",
    BLUE_YELLOW = "blueYellow",
    ALL = "all"
}
```
- bei den Werten, die nicht von Anfang an definiert werden müssen, muss man noch `nullable: true` setzen. Sonst werden die Entries nicht gespeichert. 
```typescript
 @Property({ nullable: true })
    winner?: number;
```
- wenn ich z.B. ein Game abspeichere und es wieder auslese, dann ist der Type der id immer ein string. Hannes hat das ja auch mit number angegeben, trotzdem ist es bei mir ein string. das könnte hinter her zu komischen bugs führen
- Hannes hat ja in der `server.ts` ein kleines Beispiel für die einzelnen Repositories gegeben. Wenn ich auf eines von denen zugreifen wollte, kann immer ein Error. Ich hab dann nachgelesen, dass man den Entity Manager [forken ](https://mikro-orm.io/docs/identity-map) muss 
``` typescript
const em = orm.em.fork()

export const userRepository = em.getRepository(User);
export const playerRepository = em.getRepository(Player);
```
